version: 2.1

jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    working_directory: ~/project-ml-microservice-kubernetes

    steps:
      - checkout
      - setup_remote_docker

# Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      
      - deploy:
          name: Push application Docker image
          command: |
              docker tag app "app:${CIRCLE_SHA1}"
              docker push "app:${CIRCLE_SHA1}"
            fi

workflows:
  default:
    jobs:
      - build